<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>LibraryAPI</groupId>
  <artifactId>SIDIS-LMS</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>SIDIS-LMS</name>

  <modules>
    <module>AuthServiceQuery</module>
    <module>AuthServiceCommand</module>
    <module>BookServiceQuery</module>
    <module>BookServiceCommand</module>
    <module>LendingServiceQuery</module>
    <module>LendingServiceCommand</module>
    <module>ReaderServiceQuery</module>
    <module>ReaderServiceCommand</module>
  </modules>
</project>
