@startuml
'https://plantuml.com/sequence-diagram

participant "//«component»//\nBookC1:BookServiceCommand" as BookServiceC1
participant "//«component»//\nBookC2:BookServiceCommand" as BookServiceC2
participant "//«component»//\nAuthorC1:AuthorServiceCommand" as AuthorServiceC1
participant "//«component»//\nAuthorC2:AuthorServiceCommand" as AuthorServiceC2
participant "//«component»//\nMB:MessageBroker" as MB

note left BookServiceC1
    Librarian is authenticated and initiates the creation of BAG (Book, Author, Genre)
end note

[o-> BookServiceC1: POST /api/books/createBAG\n{:book, :author, :genre}
    activate BookServiceC1
    BookServiceC1 -> BookServiceC1 : validate()
    BookServiceC1 -> BookServiceC1 : saveTempBAG()
    BookServiceC1 -> MB : publish(tempBAG, headers: serverPort)
    activate MB
[<-- BookServiceC1: 201 Created
    deactivate BookServiceC1

note over MB : Only one instance consumes the message, because they are in the same queue